### PR TITLE
Adds setuptools

### LINKED ISSUE #4: Why is setup.py empty?
The project looks great, but manipulating the `PYTHONPATH` or appending paths to the `sys.path` at runtime is a bit unconventional. 😄 I think populating the `setup.py` could make this a bit more easy to install. WDYT?

### PR DESCRIPTION
**Pull request by erip**
Makes this package installable. Fixes #4.

### CODE REVIEW

**Comment by frankseide** [comment]
Thanks! I am not familiar with installation of Python packages, but I see in the `pip` documentation an option like this:
```
[-e] git+https://git.example.com/MyProject#egg=MyProject
```
Can we use this to simplify the process even more and install it directly without explicit cloning?

**Comment by erip** [comment]
Yes. Typically folks will include the clone command in their docs because the git interop is relatively new, but pip installing a remote git repo works too.

**Comment by erip** [comment]
@frankseide As a note, though - it would eventually be great to package and ship this as a pypi (and conda) artifact so you can install it normally with `{pip, conda} install infinibatch`. CI/CD can help with this.

**Comment by erip** [comment]
Glad to help! I've noticed that the CI hasn't run yet - perhaps there's something that needs to happen on the MS side? Is this expected, @frankseide?

**Comment by frankseide** [comment]
We are looking into that. The tests are not related to the setup, but there does not seem a force-merge option on Github.

**Comment by erip** [comment]
Ok, sounds good. I've typically seen the GitHub Actions config in a [`.github/workflows`](https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#about-workflows) folder by default, but it looks like the jobs are being registered and not run, so maybe it's moot - super interesting. Let me know if there's anything I can do to help!

**Comment by frankseide** [comment]
I don't know why it does not run the tests. I have manually pulled your PR, pushed it as erip/add-setuptools, and will merge it this way. I hope this will preserve attribution correctly.

**Comment by frankseide** [comment]
Merging it myself also closed this PR automatically. Interesting. Elijah, thanks again for the first contribution to this project!

**Comment by gmyr** [comment]
The checks worked fine on @frankseide 's PR. Strange. We'll have to look into that.

Changes merged via other PR. Thanks for the contribution @erip !

**Comment by frankseide** [comment]
Elijah, did you withdraw the PR, or was Github smart enough to complete it, noticing that it had just merged the exact same thing?

And would you mind checking that your contribution was correctly accounted for in this through-the-backdoor merge process? (Insights shows 3 commits from you--thanks again!)

**Comment by erip** [comment]
It was accounted for! GitHub recognized that your "backdoor" PR was a superset (in commit history) and auto-merged/closed this. All's well and I've addressed the CI issues, too. The only lingering PR I have fixes a few documentation issues I missed originally.

**Pull request merged**
